# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1

jobs:
  test:
    parameters:
      python-version:
        type: string
      numpy-version:
        type: string
    docker:
      # specify the version you desire here
      - image: circleci/python:<<parameters.python-version>>

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install package
          command: |
            python3 -m venv venv
            . venv/bin/activate
	    pin install numpy=<<numpy-version>>
            pip install .[test]
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      # run tests
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            py.test frank/tests.py -rXs
      - store_artifacts:
          path: test-reports
          destination: test-reports

  docs-build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Install package
          command: |
            python3 -m venv venv
            . venv/bin/activate
            sudo apt-get install pandoc
            pip install jupyter_client
            pip install ipykernel
            python3 -m ipykernel install --user
            pip install .[docs-build]
      - run:
          name: Build docs
          command: |
            . venv/bin/activate
            cd docs/ && make html
      - persist_to_workspace:
          root: docs/_build
          paths: html

  docs-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: docs/_build
      - run:
          name: Disable jekyll builds
          command: touch docs/_build/html/.nojekyll
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "ci-build@ast.cam.ac.uk"
            git config user.name "ci-build"
      - add_ssh_keys:
          fingerprints:
            - "6a:8d:f2:c3:f1:0a:97:9c:86:3b:02:e7:fd:ed:ea:a6"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dotfiles --message "[skip ci] Updates" --dist docs/_build/html

workflows:
  version: 2.1
  build:
    jobs:
      - test:
          matrix:
            parameters:
              python-version: ["3.6", "3.7", "3.8"]
	      numpy-version: ["1", "4", "8", "12", "16", "18"] 
      
      - docs-build
      - docs-deploy:
          requires:
            - test
            - docs-build
          filters:
            branches:
              only: master
